# Description

This is the forth file.

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([[0], [1], [2], [3], [4]])

print(f"a + b = {a + b}")

a + b = [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
